# Section 5: Python for Data Analysis - NumPy

# 03 - Numpy operations 

In [ ]:
###Basic operations we can perform with numpy arrays:

##Array with array operations 
##Array with scalar operations 
##Array with universal array functions 

## Array with Array operations

In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
##We can perform array with array operaitons using the arithmetic operators foound in python e.g.

##Element-wise addition
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [11]:
##Element-wise subtraction and multiplication 

arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

## Array with Scalar operations

In [13]:
##When arrays are used to perform arithmetic operations with scalars, numpy performs broadcasting such that the
##arithmetic operation is also performed in an element by element basis. 

arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [14]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [15]:
arr/100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ])

In [16]:
## numpy issues a warning when division by zero occurs where nan menas not a number.
arr/arr

/home/vick/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [17]:
##Unlike Python which outputs an Error
1/0

ZeroDivisionError: division by zero

In [19]:
1/arr  ##Dividing 1 by 0 returns inf and a warning 

/home/vick/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [20]:
arr ** 2 ##Performs exponentiation

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

## Universal Array Functions

In [21]:
## Universal array functions are functions which contain mathematical operations which may be broadcasted 
## across the entire array

##sqrt of an array 

np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [22]:
##Calculating the exp of an array 
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [23]:
##Obtaining the max of an array 
np.max(arr)

10

In [24]:
arr.max()

10

In [25]:
##Trigonometric functions 
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [26]:
##Log ##Issues a warning
np.log(arr)

/home/vick/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [ ]:
###ufunc documentation - Contains all of the universal mathematical functions contained in numpy
## These functions have been optimized! -> Implement them instead of developing your own functions! 